apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubehook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubehook
        tier: worker
    spec:
      containers:
      - name: kh
        image: gcr.io/cx-network-204116/kubehook
        imagePullPolicy: Always